# Generated by Django 5.1.4 on 2025-01-15 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp_totp", "0003_add_timestamps"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUserTOTPDevice",
            fields=[
                (
                    "totpdevice_ptr",
                    models.OneToOneField(
                        auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to="otp_totp.totpdevice"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("otp_totp.totpdevice",),
        ),
        migrations.AddField(
            model_name="customuser",
            name="mfa_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
