# Generated by Django 5.1.4 on 2025-02-19 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
        ("users", "0002_customusertotpdevice_customuser_mfa_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="WalletBalance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ("currency", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="markets.cryptocurrency")),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="balances", to="users.wallet")),
            ],
            options={
                "unique_together": {("wallet", "currency")},
            },
        ),
    ]
