# Generated by Django 5.1.4 on 2025-02-19 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
        ("users", "0003_wallet_walletbalance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transaction_type", models.CharField(choices=[("deposit", "Deposit"), ("withdraw", "Withdraw")], max_length=10)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("fee", models.DecimalField(decimal_places=8, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("currency", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="markets.cryptocurrency")),
                ("wallet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.wallet")),
            ],
        ),
    ]
