# Generated by Django 5.1.4 on 2025-01-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TradingPair",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base_asset", models.CharField(max_length=10)),
                ("quote_asset", models.CharField(max_length=10)),
                ("min_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("max_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("tick_size", models.DecimalField(decimal_places=8, max_digits=20)),
                ("min_quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                ("max_quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                ("step_size", models.DecimalField(decimal_places=8, max_digits=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "trading_pairs",
                "unique_together": {("base_asset", "quote_asset")},
            },
        ),
    ]
