# Generated by Django 5.1.4 on 2025-02-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoCurrency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cryptocurrencies",
            },
        ),
        migrations.AlterField(
            model_name="tradingpair",
            name="base_asset",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="base_asset", to="markets.cryptocurrency"),
        ),
        migrations.AlterField(
            model_name="tradingpair",
            name="quote_asset",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quote_asset", to="markets.cryptocurrency"),
        ),
    ]
