version: '3.8'

services:
  web:
    build:
      context: .
      target: web
    container_name: web
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - outer
      - inner

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cert.crt:/etc/nginx/cert.crt
      - ./cert.key:/etc/nginx/cert.key
    depends_on:
      - web
    networks:
      - outer

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - inner

  redis:
    image: redis:7
    container_name: redis
    expose:
      - "6379"
    depends_on:
      - nginx
    networks:
      - inner

  celery:
    build:
      context: .
      target: web
    container_name: celery
    command: ["worker"]
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - inner

  celery_beat:
    build:
      context: .
      target: web
    container_name: celery_beat
    command: ["beat"]
    env_file:
      - .env
    depends_on:
      - celery
    networks:
      - inner

volumes:
  postgres_data:

networks:
  outer:
    driver: bridge
  inner:
    driver: bridge
