version: '3.8'

services:
  web-dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    container_name: web-dev
    ports:
      - "443:443"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db-dev
    networks:
      - outer
      - inner

  db-dev:
    image: postgres:15
    container_name: db-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - inner

  redis-dev:
    image: redis:7
    container_name: redis-dev
    expose:
      - "6379"
    networks:
      - inner

volumes:
  postgres_data:

networks:
  outer:
    driver: bridge
  inner:
    driver: bridge
