version: '3.8'

services:
  web-action:
    build:
      context: .
    container_name: web-action
    expose:
      - "8000"
    env_file:
      - .env

  db-action:
    image: postgres:15
    container_name: db-action
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_action_data:/var/lib/postgresql/data
    expose:
      - "5432"
    depends_on:
      - web-action

volumes:
  postgres_action_data:
