version: '3.8'

services:
  web-action:
    build:
      context: .
      dockerfile: Dockerfile.action
    container_name: web-action
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db-action

  db-action:
    image: postgres:15
    container_name: db-action
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

  redis-action:
    image: redis:7
    container_name: redis-action
    expose:
      - "6379"
    depends_on:
      - web-action

volumes:
  postgres_data:
