version: '3.8'

services:
  web:
    build:
      context: .
    container_name: web
    volumes:
      - .:/tradehive
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery
    command: ["worker"]
    volumes:
      - .:/tradehive
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: ["beat"]
    volumes:
      - .:/tradehive
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  postgres_data:
