FROM debian:latest

RUN apt-get update \
    && apt-get install -y iptables iproute2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY bin/setup-firewall.sh /usr/local/bin/setup-firewall.sh
RUN chmod +x /usr/local/bin/setup-firewall.sh

CMD ["/usr/local/bin/setup-firewall.sh"]
