# Generated by Django 5.1.4 on 2025-01-22 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_type", models.CharField(choices=[("market", "Market"), ("limit", "Limit")], max_length=10)),
                ("side", models.CharField(choices=[("buy", "Buy"), ("sell", "Sell")], max_length=10)),
                ("price", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="open", max_length=20)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
