# Generated by Django 5.1.4 on 2025-02-05 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("markets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_type", models.CharField(choices=[("market", "Market"), ("limit", "Limit")], max_length=10)),
                ("side", models.CharField(choices=[("buy", "Buy"), ("sell", "Sell")], max_length=10)),
                ("price", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="open", max_length=20)),
                ("base_currency", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="base_currency_orders", to="markets.cryptocurrency")),
                ("quote_currency", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quote_currency_orders", to="markets.cryptocurrency")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("buy_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="buy_trades", to="orders.order")),
                ("sell_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sell_trades", to="orders.order")),
            ],
        ),
    ]
