# Generated by Django 5.1.4 on 2025-01-22 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("buy_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="buy_trades", to="orders.order")),
                ("sell_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sell_trades", to="orders.order")),
            ],
        ),
    ]
