name: tradehive test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        group: [markets, orders, users]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup environment
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "POSTGRES_SSLMODE=${{ secrets.POSTGRES_SSLMODE }}" >> .env

          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env

          echo "CERT_CRT=${{ secrets.CERT_CRT }}" >> $GITHUB_ENV
          echo "CERT_KEY=${{ secrets.CERT_KEY }}" >> $GITHUB_ENV
          echo "PRIVATE_PEM=${{ secrets.PRIVATE_PEM }}" >> $GITHUB_ENV
          echo "PUBLIC_PEM=${{ secrets.PUBLIC_PEM }}" >> $GITHUB_ENV

      - name: Build docker compose
        run: |
          echo $CERT_CRT | base64 -d > $GITHUB_WORKSPACE/web.crt
          echo $CERT_KEY | base64 -d > $GITHUB_WORKSPACE/web.key
          echo $PRIVATE_PEM | base64 -d > $GITHUB_WORKSPACE/private.pem
          echo $PUBLIC_PEM | base64 -d > $GITHUB_WORKSPACE/public.pem

          chmod 600 $GITHUB_WORKSPACE/web.crt
          chmod 600 $GITHUB_WORKSPACE/web.key
          chmod 600 $GITHUB_WORKSPACE/private.pem
          chmod 600 $GITHUB_WORKSPACE/public.pem

          docker-compose -f docker-compose.action.yml build

      - name: Up docker compose
        run: docker-compose -f docker-compose.action.yml up -d

      - name: Test
        run: |
          if [ "${{ matrix.group }}" = "markets" ]; then
            docker-compose exec web-action python manage.py test markets -v 3
          elif [ "${{ matrix.group }}" = "orders" ]; then
            docker-compose exec web-action python manage.py test orders -v 3
          elif [ "${{ matrix.group }}" = "users" ]; then
            docker-compose exec web-action python manage.py test users -v 3
          fi
